export type ImposterCategory = {
  id: string;
  /** Shown to every player so they know the shared theme. */
  label: string;
  /** Place tokens in this theme; each phrase appears in at most one category. */
  words: readonly string[];
};

export const IMPOSTER_CATEGORIES: readonly ImposterCategory[] = [
  {
    id: "night_out",
    label: "Casinos & nightlife",
    words: [
      "casino",
      "comedy club",
      "dance hall",
      "karaoke lounge",
      "jazz club",
      "cabaret",
      "bingo hall",
      "speakeasy",
      "nightclub",
      "sports bar",
      "pool hall",
      "after-hours lounge",
    ],
  },
  {
    id: "date_spots",
    label: "Places to take your date",
    words: [
      "aquarium",
      "zoo",
      "safari park",
      "touch tank",
      "aviary",
      "reptile house",
      "butterfly pavilion",
      "penguin exhibit",
      "shark tunnel",
      "petting zoo",
      "circus",
      "big top",
      "midway",
      "fairground",
      "sideshow tent",
      "carnival lot",
      "ferris wheel",
      "carousel",
      "fun house",
      "ticket booth",
      "movie theater",
      "drive-in",
      "bowling alley",
      "planetarium",
      "art museum",
      "sculpture garden",
      "botanical garden",
      "conservatory",
      "rooftop bar",
      "ice skating rink",
      "mini golf course",
      "winery tasting room",
      "cooking class kitchen",
      "sunset pier",
      "boardwalk",
      "observatory deck",
      "dance studio",
      "IMAX theater",
      "rose garden",
      "river walk",
      "arcade date night",
    ],
  },
  {
    id: "games_shops",
    label: "Game stores & hobby shops",
    words: [
      "local game store",
      "comic shop",
      "hobby shop",
      "boardgame cafe",
      "collectibles shop",
      "card shop",
      "miniatures table",
      "RPG back room",
      "tournament hall",
      "retro game bin",
      "paint night studio",
      "escape room lobby",
    ],
  },
  {
    id: "polar",
    label: "Ice, snow & polar camps",
    words: [
      "igloo",
      "ice cave",
      "snowfield",
      "polar station",
      "ice fishing hut",
      "blizzard camp",
      "crevasse edge",
      "northern lights deck",
      "ice shelf camp",
      "snowdrift hollow",
    ],
  },
  {
    id: "continents",
    label: "Continents & giant landmasses",
    words: [
      "Africa",
      "Antarctica",
      "Asia",
      "Europe",
      "Australia",
      "North America",
      "Central America",
      "South America",
      "Sahara edge",
      "Amazon basin",
      "Great Plains",
      "Pangaea",
      "United States",
      "China",
      "India",
      "Brazil",
      "Russia",
      "Japan",
      "Germany",
      "United Kingdom",
      "France",
      "Mexico",
      "Canada",
      "Italy",
      "Egypt",
      "Nigeria",
      "Indonesia",
      "South Korea",
      "Spain",
      "Argentina",
    ],
  },
  {
    id: "home_rooms",
    label: "Rooms at home",
    words: [
      "kitchen",
      "bathroom",
      "bedroom",
      "nursery",
      "attic",
      "basement",
      "laundry room",
      "pantry",
      "study",
      "back patio",
      "front patio",
      "walk-in closet",
      "crawlspace",
      "foyer",
      "mudroom",
    ],
  },
  {
    id: "family_homes",
    label: "Houses & family places",
    words: [
      "grandma's house",
      "cottage",
      "farmhouse",
      "bungalow",
      "duplex",
      "townhouse",
      "lake house",
      "guest cottage",
      "treehouse",
      "mobile home",
      "ranch house",
      "A-frame cabin",
    ],
  },
  {
    id: "underwater",
    label: "Underwater & deep sea",
    words: [
      "underwater",
      "kelp forest",
      "shipwreck",
      "abyssal trench",
      "submarine canyon",
      "hydrothermal vent",
      "coral maze",
      "sunken ruins",
      "dive bell",
      "bathysphere",
      "cold seep",
      "seamount slope",
    ],
  },
  {
    id: "minecraft_biomes",
    label: "Minecraft biomes",
    words: [
      "sunflower plains",
      "snowy taiga",
      "mushroom fields",
      "deep dark",
      "lush caves",
      "dripstone caves",
      "nether wastes",
      "soul sand valley",
      "crimson forest",
      "warped forest",
      "end highlands",
      "end barrens",
      "small end islands",
      "stony peaks",
      "mangrove swamp",
      "windswept hills",
      "wooded badlands",
      "bamboo jungle",
      "dark forest",
      "old growth taiga",
      "cherry grove",
      "meadow",
      "basalt deltas",
      "frozen peaks",
      "jagged peaks",
      "sparse jungle",
    ],
  },
  {
    id: "star_wars_planets",
    label: "Star Wars planets & moons",
    words: [
      "Tatooine",
      "Hoth",
      "Endor",
      "Coruscant",
      "Naboo",
      "Mustafar",
      "Dagobah",
      "Jakku",
      "Bespin",
      "Geonosis",
      "Mandalore",
      "Ahch-To",
      "Scarif",
      "Kashyyyk",
      "Utapau",
      "Alderaan",
      "Yavin 4",
      "Dathomir",
      "Exegol",
      "Crait",
      "Felucia",
      "Kamino",
      "Ryloth",
      "Mon Cala",
      "Batuu",
      "Jedha",
    ],
  },
  {
    id: "medieval_fantasy",
    label: "Medieval fantasy",
    words: [
      "tavern common room",
      "castle keep",
      "dungeon",
      "wizard tower",
      "throne room",
      "village square",
      "blacksmith forge",
      "monastery cloister",
      "drawbridge",
      "curtain wall walk",
      "stables",
      "market cross",
      "healing tent",
      "guild hall",
      "catacombs",
      "inner bailey",
      "motte hill",
      "watchtower",
      "alchemist workshop",
      "portcullis gate",
      "arrow slit gallery",
      "great hall hearth",
    ],
  },
  {
    id: "pirate_ship",
    label: "On a pirate ship",
    words: [
      "brig",
      "crow's nest",
      "captain's cabin",
      "orlop deck",
      "gun deck",
      "cargo hold",
      "chart room",
      "rope locker",
      "fo'c'sle",
      "quarterdeck",
      "bilge",
      "powder magazine",
      "carpenter's shop",
      "capstan deck",
      "stern gallery",
      "gundeck hatch",
      "mess deck",
      "skysail yard",
      "rudder post",
      "chain locker",
    ],
  },
  {
    id: "vehicles",
    label: "Vehicles & vehicle areas",
    words: [
      "parking garage",
      "gas station",
      "EV charging lot",
      "car wash",
      "DMV lobby",
      "toll plaza",
      "weigh station",
      "rest stop",
      "bus depot",
      "taxi stand",
      "subway platform",
      "train yard",
      "racetrack pit lane",
      "ferry terminal",
      "airport gate",
      "jet bridge",
      "rental car counter",
      "truck stop",
      "roundabout merge",
      "charging station canopy",
    ],
  },
  {
    id: "outer_space",
    label: "Outer space & sci-fi locales",
    words: [
      "outer space",
      "spaceship",
      "space station",
      "satellite",
      "launchpad",
      "lunar base",
      "asteroid mine",
      "airlock",
      "cargo bay",
      "nebula",
      "orbit",
      "zero-g lab",
      "colony dome",
      "solar sail dock",
      "cryosleep bay",
    ],
  },
  {
    id: "armor_yard",
    label: "Tanks & motor pools",
    words: [
      "tank",
      "motor pool",
      "armor bay",
      "proving ground",
      "revetment",
      "hangar bay",
      "maintenance pit",
      "gun range",
      "storage depot",
      "convoy yard",
      "reloading trench",
      "camo net yard",
    ],
  },
  {
    id: "skyscrapers",
    label: "Skyscrapers & towers",
    words: [
      "skyscraper",
      "penthouse",
      "observation deck",
      "express elevator",
      "sky lobby",
      "rooftop garden",
      "helipad",
      "curtain wall",
      "spire lounge",
      "skybridge",
    ],
  },
  {
    id: "great_outdoors",
    label: "Forests, deserts & open land",
    words: [
      "forest",
      "swamp",
      "plains",
      "mountain",
      "island",
      "desert",
      "volcano",
      "grove",
      "hidden grotto",
      "jungle",
      "prairie",
      "savanna",
      "canyon",
      "moor",
      "badlands",
      "oasis",
      "river delta",
      "cliff overlook",
    ],
  },
  {
    id: "cruise_ships",
    label: "Cruise ships & liners",
    words: [
      "cruise ship",
      "ocean liner",
      "ferry",
      "liner promenade deck",
      "liner galley",
      "cabin corridor",
      "bridge wing",
      "lifeboat station",
      "pool deck",
      "buffet line",
      "shore excursion dock",
      "liner theater",
      "spa deck",
    ],
  },
  {
    id: "private_moments",
    label: "Private & washroom spots",
    words: [
      "on the toilet",
      "powder room",
      "water closet",
      "restroom stall",
      "lavatory",
      "shower stall",
      "changing stall",
      "locker washroom",
      "spa bathroom",
      "outhouse",
      "bidet nook",
    ],
  },
  {
    id: "datacenters",
    label: "AI & datacenters",
    words: [
      "AI datacenter",
      "datacenter",
      "server room",
      "cold aisle",
      "hot aisle",
      "NOC",
      "supercomputer hall",
      "render farm",
      "colocation cage",
      "fiber vault",
      "UPS gallery",
      "GPU hall",
      "liquid cooling loop",
    ],
  },
] as const;
