export type SpyfallCategory = {
  id: string;
  /** Shown to every player so they know the shared theme. */
  label: string;
  /** Place tokens in this theme; each phrase appears in at most one category. */
  words: readonly string[];
};

export const SPYFALL_CATEGORIES: readonly SpyfallCategory[] = [
  {
    id: "date_spots",
    label: "Nights out & date spots",
    words: [
      "casino",
      "comedy club",
      "dance hall",
      "karaoke lounge",
      "jazz club",
      "bingo hall",
      "speakeasy",
      "nightclub",
      "sports bar",
      "pool hall",
      "aquarium",
      "zoo",
      "mall",
      "safari park",
      "aviary",
      "reptile house",
      "butterfly pavilion",
      "penguin exhibit",
      "shark tunnel",
      "petting zoo",
      "circus",
      "big top",
      "midway",
      "fairground",
      "sideshow tent",
      "carnival lot",
      "ferris wheel",
      "carousel",
      "fun house",
      "ticket booth",
      "movie theater",
      "drive-in",
      "bowling alley",
      "planetarium",
      "art museum",
      "sculpture garden",
      "botanical garden",
      "conservatory",
      "rooftop bar",
      "ice skating rink",
      "mini golf course",
      "winery tasting room",
      "cooking class kitchen",
      "sunset pier",
      "boardwalk",
      "observatory deck",
      "dance studio",
      "rose garden",
      "river walk",
      "arcade",
      "local game store",
      "comic shop",
      "boardgame cafe",
      "cat cafe",
      "collectibles shop",
      "card shop",
      "tournament hall",
      "retro game bin",
      "paint night studio",
      "escape room lobby",
    ],
  },
  {
    id: "polar",
    label: "Ice, snow & polar camps",
    words: [
      "igloo",
      "ice cave",
      "snowfield",
      "polar station",
      "ice fishing hut",
      "blizzard camp",
      "northern lights deck",
      "ice shelf camp",
      "snowdrift hollow",
    ],
  },
  {
    id: "continents",
    label: "Continents & giant landmasses",
    words: [
      "Africa",
      "Antarctica",
      "Asia",
      "Europe",
      "Australia",
      "North America",
      "Central America",
      "South America",
      "Sahara edge",
      "Amazon basin",
      "Great Plains",
      "Pangaea",
      "United States",
      "China",
      "India",
      "Brazil",
      "Russia",
      "Japan",
      "Germany",
      "United Kingdom",
      "France",
      "Mexico",
      "Canada",
      "Italy",
      "Egypt",
      "Nigeria",
      "Indonesia",
      "South Korea",
      "Spain",
      "Argentina",
      "Pacific Ocean",
      "Atlantic Ocean",
      "Indian Ocean",
      "Southern Ocean",
      "Arctic Ocean",
      "Antarctic Ocean",
    ],
  },
  {
    id: "home_rooms",
    label: "Rooms at home",
    words: [
      "kitchen",
      "bathroom",
      "bedroom",
      "nursery",
      "attic",
      "basement",
      "laundry room",
      "pantry",
      "study",
      "back patio",
      "shower",
      "bathroom",
      "living room",
      "dining room",
      "office",
      "front patio",
      "walk-in closet",
      "crawlspace",
      "foyer",
      "guest room",
      "hallway",
      "garage",
      "room under the stairs",
      "storage room",
    ],
  },
  {
    id: "underwater",
    label: "Underwater & deep sea",
    words: [
      "underwater",
      "kelp forest",
      "shipwreck",
      "abyssal trench",
      "submarine canyon",
      "hydrothermal vent",
      "coral maze",
      "sunken ruins",
      "dive bell",
      "sea monster's den",
      "mermaid lagoon",
      "kraken's lair",
      "cold seep",
      "seamount slope",
    ],
  },
  {
    id: "minecraft_biomes",
    label: "Minecraft biomes",
    words: [
      "sunflower plains",
      "snowy taiga",
      "mushroom fields",
      "deep dark",
      "lush caves",
      "dripstone caves",
      "nether wastes",
      "soul sand valley",
      "crimson forest",
      "warped forest",
      "the end",
      "outer end islands",
      "stony peaks",
      "mangrove swamp",
      "windswept hills",
      "wooded badlands",
      "bamboo jungle",
      "dark forest",
      "old growth taiga",
      "cherry grove",
      "meadow",
      "basalt deltas",
      "frozen peaks",
      "jagged peaks",
      "sparse jungle",
      "village",
      "desert temple",
      "jungle temple",
      "savanna",
      "beach",
      "jungle",
      "cave",
      "river",
      "forest",
      "birch forest",
      "mooshroom island",
    ],
  },
  {
    id: "star_wars_planets",
    label: "Star Wars planets & moons",
    words: [
      "Tatooine",
      "Hoth",
      "Endor",
      "Coruscant",
      "Naboo",
      "Mustafar",
      "Dagobah",
      "Jakku",
      "Bespin",
      "Geonosis",
      "Mandalore",
      "Scarif",
      "Kashyyyk",
      "Utapau",
      "Alderaan",
      "Yavin 4",
      "Dathomir",
      "Exegol",
      "Crait",
      "Kamino",
      "Jedha",
    ],
  },
  {
    id: "medieval_fantasy",
    label: "Medieval fantasy",
    words: [
      "tavern",
      "castle keep",
      "dungeon",
      "wizard tower",
      "treasure room",
      "docks",
      "bridge",
      "throne room",
      "village square",
      "blacksmith forge",
      "monastery",
      "drawbridge",
      "stables",
      "market cross",
      "healing tent",
      "guild hall",
      "catacombs",
      "inner bailey",
      "motte hill",
      "watchtower",
      "library",
      "alchemist workshop",
      "portcullis",
      "arrow slit gallery",
      "great hall hearth",
      "barracks",
    ],
  },
  {
    id: "pirate_ship",
    label: "On a pirate ship",
    words: [
      "brig",
      "crow's nest",
      "captain's cabin",
      "orlop deck",
      "gun deck",
      "cargo hold",
      "chart room",
      "rope locker",
      "fo'c'sle",
      "quarterdeck",
      "bilge",
      "powder magazine",
      "carpenter's shop",
      "capstan deck",
      "stern gallery",
      "mess deck",
      "skysail yard",
      "rudder post",
      "davy jones' locker",
    ],
  },
  {
    id: "vehicles",
    label: "Vehicles & vehicle areas",
    words: [
      "parking garage",
      "gas station",
      "EV charging lot",
      "car wash",
      "airplane",
      "aircraft carrier",
      "helicopter",
      "boat",
      "train",
      "personal vehicle",
      "motorcycle",
      "bicycle",
      "scooter",
      "skateboard",
      "DMV lobby",
      "rest stop",
      "bus depot",
      "taxi stand",
      "subway platform",
      "train yard",
      "tram stop",
      "racetrack pit lane",
      "ferry terminal",
      "airport gate",
      "truck stop",
      "traffic light",
      "stop sign intersection",
      "roundabout merge",
      "charging station canopy",
    ],
  },
  {
    id: "outer_space",
    label: "Outer space & sci-fi locales",
    words: [
      "outer space",
      "spaceship",
      "space station",
      "satellite",
      "launchpad",
      "lunar base",
      "asteroid mine",
      "airlock",
      "cargo bay",
      "nebula",
      "orbit",
      "zero-g lab",
      "colony dome",
      "solar sail dock",
      "cryosleep bay",
    ],
  },
  {
    id: "city_locations",
    label: "City locations",
    words: [
      "downtown",
      "financial district",
      "city hall steps",
      "public square",
      "mall",
      "brick alley",
      "skyscraper lobby",
      "high-rise atrium",
      "office tower floor",
      "express elevator bank",
      "penthouse terrace",
      "rooftop helipad",
      "convention center hall",
      "hotel atrium",
      "department store aisle",
      "sidewalk cafe strip",
      "food hall",
      "street vendor row",
      "subway mezzanine",
      "bus kiosk corner",
      "library front steps",
      "courthouse plaza",
      "post office arcade",
      "neon sign district",
      "warehouse district",
      "pocket park bench",
      "city park fountain",
      "underground passage",
      "skyline overlook",
      "chinatown",
      "subway station",
    ],
  },
  {
    id: "great_outdoors",
    label: "Forests, deserts & open land",
    words: [
      "forest",
      "swamp",
      "plains",
      "mountain",
      "island",
      "desert",
      "volcano",
      "grove",
      "hidden grotto",
      "jungle",
      "prairie",
      "savanna",
      "canyon",
      "moor",
      "badlands",
      "oasis",
      "river delta",
      "cliff overlook",
      "cave",
      "river",
      "forest",
      "birch forest",
      "mangrove swamp",
      "volcanic island",
      "tundra",
      "gorge",
      "valley",
    ],
  },
  {
    id: "cruise_ships",
    label: "Cruise ships & liners",
    words: [
      "cruise ship",
      "ocean liner",
      "ferry",
      "promenade deck",
      "liner galley",
      "cabin corridor",
      "bridge wing",
      "lifeboat station",
      "pool deck",
      "buffet line",
      "shore excursion dock",
      "spa deck",
      "pool",
      "gym",
      "captain's cabin",
      "atrium",
      "gangway",
      "lounge",
      "food court",
      "bar",
      "muster station",
      "poop deck",
      "brig",
      "galley",
      "scullery",
    ],
  },
] as const;
